### PR TITLE
(No review) Update version number

### PR DESCRIPTION
**Pull request by nickhurlburt**
Pair programmed with @yschatzberg

### CODE REVIEW

**Comment by KaoruDev** [comment]
@nickhurlburt did you push the gem up to rubygems.org?

**Comment by nickhurlburt** [comment]
Yep! https://rubygems.org/gems/sift-partner/versions/0.0.4

**Comment by KaoruDev** [comment]
🔥 awesome, could you also add the tag to the repo please?

**Comment by nickhurlburt** [comment]
Good call, thanks!  Done.

On Fri, Jul 1, 2016 at 12:19 PM, Kaoru Kohashigawa <notifications@github.com

**Pull request merged**
