### PR TITLE
(For Aaron) Change get_accounts to handle limited results

### PR DESCRIPTION
**Pull request by nickhurlburt**
@abeppu Introduces ability to pass a `next_ref` URL to get pages in get_accounts.

cc @yschatzberg

### CODE REVIEW

**Comment by abeppu** [comment]
As with the python version, this seems fine. However, could you expand the get_accounts test to check next_ref ? https://github.com/SiftScience/sift-partner-ruby/blob/master/spec/unit/client_spec.rb#L125

**Comment by nickhurlburt** [comment]
Test changed to include test of next_ref.

**Comment by nickhurlburt** [comment]
Updated.

**Comment by abeppu** [comment]
LGTM

**Pull request merged**
